-- insert the retrieved data into historical db

INSERT INTO "historical_records" ("lesson_type", "genre", "instrument", "lesson_price", "student_first_name", "student_last_name", "student_email") VALUES

('Individual',''	, 	'Flute',	199.98,	'Hans',	'Holmqvist',	'hans.holm@example.com'),
('Individual',''	,	'Guitar',	199.98,	'Andreas',	'Johansson'	,'andreas.johansson@example.com'),
('Individual',''	,	'Drums'	,199.98	,'Linnea'	,'Gustavsson'	,'linnea.gustavsson@example.com'),
('Individual',''	,	'Violin'	,259.98	,'Sune'	,'Jansson',	'sune.jansson@example.com'),
('Individual',''	,	'Guitar',	199.98,	'Niklas',	'Gustafsson',	'niklas.gustafsson@example.com'),

('Group', '' ,		'Piano'	, 220,	'Anders',	'Eriksson'	,'anders.eriksson@example.com'),
('Group', '',		'Piano'	,220	,'Sara'	,'Olsson',	'sara.olsson@example.com'),
('Group',	'',	'Piano'	,220	,'Mattias'	,'Olsson'	,'mattias.olsson@example.com'),
('Group',''	,	'Piano'	,220	,'Ingrid'	,'Olofsson',	'ingrid.olofsson@example.com'),
('Group',''	,	'Piano'	,220	,'Siv'	,'Karlsson',	'siv.karlsson@example.com'),
('Group',''	,	'Clarinet'	,265	,'Andreas',	'Persson',	'andreas.persson@example.com'),
('Group',''	,	'Clarinet'	,265	,'Allan',	'Hansen'	,'allan.hansen@example.com'),
('Group',''	,	'Clarinet',	265	,'Anneli',	'Vikström',	'anneli.vikström@example.com'),
('Group',''	,	'Clarinet'	,265	,'Erika'	,'Persson',	'erika.persson@example.com'),
('Group',''	,	'Clarinet'	,265	,'Olof',	'Lindgren'	,'olof.lindgren@example.com'),
('Group',''	,	'Violin',	220	,'Tomas',	'Svensson',	'tomas.svensson@example.com'),
('Group',''	,	'Violin',	220	,'Gustaf',	'Lindén',	'gustaf.lindén@example.com'),
('Group',''	,	'Violin',	220	,'Josef',	'Eriksson',	'josef.eriksson@example.com'),
('Group',''	,	'Violin',	220	,'Jennie',	'Sandström'	,'jennie.sandström@example.com'),
('Group',''	,	'Violin',	220,	'Tage',	'Nilsson',	'tage.nilsson@example.com'),
('Group',''	,	'Drums'	,220	,'Carl'	,'Lindgren',	'carl.lindgren@example.com'),
('Group',''	,	'Drums'	,220	,'Inger'	,'Norberg'	,'inger.norberg@example.com'),
('Group',''	,	'Drums', 220,	'Kjell',	'Lindholm',	'kjell.lindholm@example.com'),
('Group',''	,	'Drums'	,220	,'Cecilia'	,'Karlsson'	,'cecilia.karlsson@example.com'),
('Group',''	,	'Drums'	,220	,'Hillevi'	,'Lundberg',	'hillevi.lundberg@example.com'),
('Group',''	,   'Flute'	,265	,'Per',	'Lindberg',	'per.lindberg@example.com'),
('Group',''	,	'Flute',	265	,'Victor',	'Andersson'	,'victor.andersson@example.com'),
('Group',''	,	'Flute',	265	,'Margareta',	'Melin',	'margareta.melin@example.com'),

('Ensemble', 'Jazz'	,'',	249.98,	'Andreas'	,'Persson'	,'andreas.persson@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Erik',	'Johansson',	'erik.johan@example.com'),
('Ensemble',	'Jazz'	, '' ,	249.98,	'Siv',	'Karlsson',	'siv.karlsson@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Olof'	,'Lindgren',	'olof.lindgren@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Lars',	'Fransson',	'lars.fransson@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Olof'	,'Pettersson',	'olof.pettersson@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Jennie',	'Sandström'	,'jennie.sandström@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Anneli','Vikström'	,'anneli.vikström@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Holger'	,'Olsson'	,'holger.olsson@example.com'),
('Ensemble',	'Jazz'	,'',	249.98	,'Ester'	,'Karlsson',	'ester.karlsson@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Birgit'	,'Gustafsson'	,'birgit.gustafsson@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Cecilia'	,'Karlsson'	,'cecilia.karlsson@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Malin'	,'Pettersson',	'malin.pettersson@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Kjell',	'Lindholm'	,'kjell.lindholm@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Inger'	,'Norberg',	'inger.norberg@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Carl',	'Lindgren',	'carl.lindgren@example.com'),
('Ensemble',	'Rock'	,'',	249.98	,'Hillevi'	,'Lundberg',	'hillevi.lundberg@example.com'),
('Ensemble',	'Blues'	,'',	249.98	,'Inger',	'Norberg'	,'inger.norberg@example.com'),
('Ensemble',	'Blues'	,'',	249.98	,'Carl'	,'Lindgren'	,'carl.lindgren@example.com'),
('Ensemble',	'Blues'	,'',	249.98	,'Hillevi',	'Lundberg',	'hillevi.lundberg@example.com'),
('Ensemble',	'Blues'	,'',	249.98	,'Cecilia'	,'Karlsson',	'cecilia.karlsson@example.com'),
('Ensemble',	'Blues'	,'',	249.98	,'Kjell'	,'Lindholm'	,'kjell.lindholm@example.com'),
('Ensemble',	'Jazz'	,'',	270	,'Tobias'	,'Bengtsson',	'tobias.bengtsson@example.com'),
('Ensemble',	'Jazz'	,'',	270	,'Vilhelm'	,'Axelsson'	,'vilhelm.axelsson@example.com'),
('Ensemble',	'Country','',		249.98	,'Karl'	,'Svensson'	,'karl.svensson@example.com');